# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimizeAnchors <- function(scaledData, Rclasses, anchors, attractG, repelG, law, steps, normalizeExamples) {
    .Call('_Radviz_optimizeAnchors', PACKAGE = 'Radviz', scaledData, Rclasses, anchors, attractG, repelG, law, steps, normalizeExamples)
}

optimizeAnchors2 <- function(scaledData, Rclasses, anchors, RclustWeights, attractG, repelG, law, steps, normalizeExamples) {
    .Call('_Radviz_optimizeAnchors2', PACKAGE = 'Radviz', scaledData, Rclasses, anchors, RclustWeights, attractG, repelG, law, steps, normalizeExamples)
}

optimizeAnchorsGraph <- function(scaledData, RedgesInds, RedgeWeights, RdegreeVect, anchors, attractG, repelG, law, steps, normalizeExamples) {
    .Call('_Radviz_optimizeAnchorsGraph', PACKAGE = 'Radviz', scaledData, RedgesInds, RedgeWeights, RdegreeVect, anchors, attractG, repelG, law, steps, normalizeExamples)
}

